// Rick and Morty's finest
export const origins = [
	'Mortytown',
	'Pluto',
	'Flump',
	'Teenyverse',
	'Froopyland',
	'Corn Universe',
	'Midland Quasar',
	'Big Pluto',
	"Lil' Bits",
	'Blumbus Dimension',
	'Krumpf',
	'Merged Universe',
	'Miniverse',
	'Nuptia 4',
	'Cogspot',
	'Comulon Dimension',
	'Parblesnops',
	'Pawn Shop Planet',
	'Plim Plom Tavern',
	'Doopidoo Dimension',
	'Zorpantheon 9',
];
